base_path: '/home/andy/projects/gplvote.signdoc.client'
pid_file: '/var/run/gplvote.signdoc.client.pid'
log_file: '/var/log/projects/gplvote.signdoc.client.log'
cmd_path: '/home/andy/projects/gplvote.signdoc.client/server/signdoc-client-server.pl "/home/andy/projects/gplvote.signdoc.client/server/config.yml"'
product_name: 'gplvote.client.signdoc'
site: 'client_signdoc.gplvote.org'
fcgi:
  host: '127.0.0.1'
  port: '9002'
  listen_queue: 128
  nprocs: 1
  min_nprocs: 1
  max_nprocs: 4
  delta_nprocs: 1
  delta_time: 60
  max_requests: 300
db:
  host: '127.0.0.1'
  port: '5432'
  name: 'signdoc_client'
  user: 'postgres'
  password: ''
